import AuthProvider from "@/components/authProvider"

export const metadata = {
  title: 'Latin Certamen Quizbowl Prototype',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </AuthProvider>
  )
}
